version: '3'
services:
  db:
    image: mysql:8.0
    volumes:
      - db-volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      TZ: Asia/Tokyo
  app:
    build: .
    command: bundle exec pumactl start
    volumes:
      - .:/app
      - ./public:/app/public
      - ./tmp:/app/tmp
      - ./log:/app/log
    ports:
      - "3000:3000"
    depends_on:
      - db
    tty: true
    stdin_open: true
  nginx:
    build: containers/nginx
    volumes:
      - ./public:/app/public
      - ./tmp:/app/tmp
    ports:
      - 80:80
    depends_on:
      - app
volumes:
  db-volume: